import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';


@Component({
  selector: 'app-driver-enter-otp',
  imports: [FormsModule,CommonModule],
  templateUrl: './driver-enter-otp.html',
  styleUrl: './driver-enter-otp.css'
})
export class DriverEnterOtp implements OnInit {
  enteredOtp: string = '';
  otpValid: boolean = false;
  otpInvalid: boolean = false;
  isLoading: boolean = false;
  
  // Driver credentials from previous step
  email: string = '';
  mobile: string = '';
  driverId: string = '';
  
  private readonly correctOtp = '123456'; // This would be generated by backend in real implementation
  
  constructor(private router: Router, private route: ActivatedRoute) {}
  
  ngOnInit() {
    // Get email, mobile, and driverId from query parameters
    this.route.queryParams.subscribe(params => {
      this.email = params['email'] || '';
      this.mobile = params['mobile'] || '';
      this.driverId = params['driverId'] || '';
      
      console.log('OTP component initialized with:', {
        email: this.email,
        mobile: this.mobile,
        driverId: this.driverId
      });
    });
  }
  
  onValidateOtp() {
    console.log(' Validating OTP:', this.enteredOtp);
    
    if (!this.enteredOtp.trim()) {
      this.otpInvalid = true;
      this.otpValid = false;
      return;
    }
    
    this.isLoading = true;
    
    
    if (this.enteredOtp === this.correctOtp) {
      this.otpValid = true;
      this.otpInvalid = false;
      
      console.log('✅ OTP validated successfully');
      
      // Redirect to set new password with credentials
      setTimeout(() => {
        this.router.navigate(['/main/driversetnewpassword'], {
          queryParams: {
            email: this.email,
            mobile: this.mobile,
            driverId: this.driverId
          }
        });
      }, 1500);
    } else {
      this.isLoading = false;
      this.otpInvalid = true;
      this.otpValid = false;
      console.log('❌ Invalid OTP entered');
    }
  }
             
}
